# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DlgSQLSettings'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(352, 215)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(12, 164, 331, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 8, 160, 155))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.btOk = QtWidgets.QPushButton(Dialog)
        self.btOk.setGeometry(QtCore.QRect(174, 180, 75, 23))
        self.btOk.setObjectName("btOk")
        self.btCancel = QtWidgets.QPushButton(Dialog)
        self.btCancel.setGeometry(QtCore.QRect(264, 180, 75, 23))
        self.btCancel.setObjectName("btCancel")
        self.etPassword = QtWidgets.QTextEdit(Dialog)
        self.etPassword.setGeometry(QtCore.QRect(180, 134, 160, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.etPassword.sizePolicy().hasHeightForWidth())
        self.etPassword.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.etPassword.setFont(font)
        self.etPassword.setAcceptDrops(False)
        self.etPassword.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.etPassword.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.etPassword.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.etPassword.setObjectName("etPassword")
        self.etConnectName = QtWidgets.QTextEdit(Dialog)
        self.etConnectName.setGeometry(QtCore.QRect(180, 12, 160, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.etConnectName.sizePolicy().hasHeightForWidth())
        self.etConnectName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.etConnectName.setFont(font)
        self.etConnectName.setAcceptDrops(False)
        self.etConnectName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.etConnectName.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.etConnectName.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.etConnectName.setObjectName("etConnectName")
        self.etUserName = QtWidgets.QTextEdit(Dialog)
        self.etUserName.setGeometry(QtCore.QRect(180, 106, 160, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.etUserName.sizePolicy().hasHeightForWidth())
        self.etUserName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.etUserName.setFont(font)
        self.etUserName.setAcceptDrops(False)
        self.etUserName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.etUserName.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.etUserName.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.etUserName.setObjectName("etUserName")
        self.etPort = QtWidgets.QTextEdit(Dialog)
        self.etPort.setGeometry(QtCore.QRect(180, 74, 160, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.etPort.sizePolicy().hasHeightForWidth())
        self.etPort.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.etPort.setFont(font)
        self.etPort.setAcceptDrops(False)
        self.etPort.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.etPort.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.etPort.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.etPort.setObjectName("etPort")
        self.etHostName = QtWidgets.QTextEdit(Dialog)
        self.etHostName.setGeometry(QtCore.QRect(180, 42, 160, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.etHostName.sizePolicy().hasHeightForWidth())
        self.etHostName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.etHostName.setFont(font)
        self.etHostName.setAcceptDrops(False)
        self.etHostName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.etHostName.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.etHostName.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.etHostName.setObjectName("etHostName")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MySQL - New Connection"))
        self.label.setText(_translate("Dialog", "Connection Name:"))
        self.label_2.setText(_translate("Dialog", "Host Name/IP Address"))
        self.label_3.setText(_translate("Dialog", "Port"))
        self.label_4.setText(_translate("Dialog", "User Name"))
        self.label_5.setText(_translate("Dialog", "Password"))
        self.btOk.setText(_translate("Dialog", "Ok"))
        self.btCancel.setText(_translate("Dialog", "Cancel"))
