# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiMain'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(866, 663)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setTabletTracking(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 866, 23))
        self.menubar.setObjectName("menubar")
        self.menudasw = QtWidgets.QMenu(self.menubar)
        self.menudasw.setObjectName("menudasw")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setMinimumSize(QtCore.QSize(80, 0))
        self.dockWidgetContents.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dockWidgetContents.setAutoFillBackground(False)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.trConnect = QtWidgets.QTreeWidget(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trConnect.sizePolicy().hasHeightForWidth())
        self.trConnect.setSizePolicy(sizePolicy)
        self.trConnect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.trConnect.setAutoFillBackground(False)
        self.trConnect.setFrameShape(QtWidgets.QFrame.Box)
        self.trConnect.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.trConnect.setAutoScrollMargin(16)
        self.trConnect.setAlternatingRowColors(False)
        self.trConnect.setItemsExpandable(True)
        self.trConnect.setAnimated(False)
        self.trConnect.setAllColumnsShowFocus(False)
        self.trConnect.setHeaderHidden(True)
        self.trConnect.setExpandsOnDoubleClick(True)
        self.trConnect.setObjectName("trConnect")
        self.trConnect.headerItem().setText(0, "1")
        self.trConnect.header().setVisible(False)
        self.verticalLayout.addWidget(self.trConnect)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_2.setFloating(False)
        self.dockWidget_2.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_2.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tbField = QtWidgets.QTableWidget(self.dockWidgetContents_2)
        self.tbField.setObjectName("tbField")
        self.tbField.setColumnCount(0)
        self.tbField.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tbField)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)
        self.dockWidget_3 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_3.setFloating(False)
        self.dockWidget_3.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_3.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tbData = QtWidgets.QTableWidget(self.dockWidgetContents_3)
        self.tbData.setObjectName("tbData")
        self.tbData.setColumnCount(0)
        self.tbData.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tbData)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_3)
        self.actionMySQL = QtWidgets.QAction(MainWindow)
        self.actionMySQL.setCheckable(True)
        self.actionMySQL.setStatusTip("")
        font = QtGui.QFont()
        font.setKerning(False)
        self.actionMySQL.setFont(font)
        self.actionMySQL.setAutoRepeat(False)
        self.actionMySQL.setIconVisibleInMenu(True)
        self.actionMySQL.setObjectName("actionMySQL")
        self.cmdNewMySQLConnect = QtWidgets.QAction(MainWindow)
        self.cmdNewMySQLConnect.setObjectName("cmdNewMySQLConnect")
        self.actionQt = QtWidgets.QAction(MainWindow)
        self.actionQt.setObjectName("actionQt")
        self.actionGlobalView = QtWidgets.QAction(MainWindow)
        self.actionGlobalView.setObjectName("actionGlobalView")
        self.actionDataView = QtWidgets.QAction(MainWindow)
        self.actionDataView.setObjectName("actionDataView")
        self.actionFieldCommandView = QtWidgets.QAction(MainWindow)
        self.actionFieldCommandView.setObjectName("actionFieldCommandView")
        self.actionDataCommandView = QtWidgets.QAction(MainWindow)
        self.actionDataCommandView.setObjectName("actionDataCommandView")
        self.actionFieldView = QtWidgets.QAction(MainWindow)
        self.actionFieldView.setObjectName("actionFieldView")
        self.menudasw.addAction(self.cmdNewMySQLConnect)
        self.menuAbout.addAction(self.actionQt)
        self.menuView.addAction(self.actionGlobalView)
        self.menuView.addAction(self.actionFieldView)
        self.menuView.addAction(self.actionDataView)
        self.menuView.addAction(self.actionFieldCommandView)
        self.menuView.addAction(self.actionDataCommandView)
        self.menubar.addAction(self.menudasw.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SQL CRUD"))
        self.menudasw.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "GlobalView"))
        self.dockWidget_2.setWindowTitle(_translate("MainWindow", "Field View"))
        self.dockWidget_3.setWindowTitle(_translate("MainWindow", "Data"))
        self.actionMySQL.setText(_translate("MainWindow", "MySQL"))
        self.cmdNewMySQLConnect.setText(_translate("MainWindow", "New Connection to MySQL"))
        self.actionQt.setText(_translate("MainWindow", "Qt"))
        self.actionGlobalView.setText(_translate("MainWindow", "GlobalView"))
        self.actionDataView.setText(_translate("MainWindow", "DataView"))
        self.actionFieldCommandView.setText(_translate("MainWindow", "FieldCommandView"))
        self.actionDataCommandView.setText(_translate("MainWindow", "DataCommandView"))
        self.actionFieldView.setText(_translate("MainWindow", "FieldView"))
